# Generated by Django 5.2.6 on 2025-11-13 17:32

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
