# Generated by Django 5.2.6 on 2025-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='profile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
