# Generated by Django 5.2.6 on 2025-11-17 18:29

from django.db import migrations


class Migration(migrations.Migration):
    def create_user_profiles(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        Profile = apps.get_model('users', 'Profile')

        for user in User.objects.all():
            # Only create if it doesn’t already exist
            if not hasattr(user, 'profile'):
                Profile.objects.create(user=user)


    dependencies = [
        ('users', '0006_remove_profile_is_suspended_profile_suspended_until'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
