# Generated by Django 5.2.6 on 2025-11-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_nickname'),
        ('users', '0007_auto_20251117_1329'),
    ]

    operations = [
    ]
