# Generated by Django 5.2.6 on 2025-11-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0006_profile_nickname_0007_auto_20251117_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
