# Generated by Django 5.2.6 on 2025-12-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_student_email_profile_student_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, verbose_name='bio'),
        ),
    ]
