# Generated by Django 5.2.6 on 2025-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
