# Generated by Django 5.2.6 on 2025-11-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
