# Generated by Django 5.2.6 on 2025-11-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_userprofile'),
        ('login', '0002_remove_userprofile_is_suspended_and_more'),
    ]

    operations = [
    ]
