# Generated by Django 5.2.6 on 2025-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Like New'), (3, 'Good'), (4, 'Fair'), (5, 'Poor')], default=3),
        ),
    ]
