# Generated by Django 5.2.6 on 2025-12-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
