# Generated by Django 5.2.6 on 2025-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeals',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined'), ('P', 'Pending')], default='pending', max_length=20),
        ),
    ]
