# Generated by Django 5.2.6 on 2025-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_appeals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeals',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined'), ('P', 'Pending')], default='Pending', max_length=20),
        ),
    ]
