# Generated by Django 5.2.6 on 2025-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
